# Generated by Django 5.1.3 on 2024-11-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('collected_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
