# Generated by Django 5.1.3 on 2024-11-27 06:05

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
